# Prometheus Configuration for Toll Hub
# Provides comprehensive monitoring and alerting for the entire platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'tollhub'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Authentication Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Toll Service
  - job_name: 'toll-service'
    static_configs:
      - targets: ['toll-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Statement Service
  - job_name: 'statement-service'
    static_configs:
      - targets: ['statement-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Agency Service
  - job_name: 'agency-service'
    static_configs:
      - targets: ['agency-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Docker Daemon (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']
    scrape_interval: 30s
